[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qtinfra-demo"
version = "0.1.0"
description = "Clean-room enterprise-style quant trading infrastructure demo"
requires-python = ">=3.11"